language: ruby
rvm:
  - 2.4
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --white-list https://travis-ci.org/calee0219/awesome-5g.svg?branch=main
notifications:
  email: false
